name: test-mongodb

on: [push]

jobs:
  test-mongodb:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    services:
      mongodb:
        image: mongo:3.4.23
        ports:
          - 27017:27017
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Set up as module
      run: |
        HERE=`pwd`
        mkdir /tmp/project
        cd /tmp/project
        npm init -y
        npm install faker puppeteer@2.1.1 @userdashboard/dashboard @userdashboard/storage-mongodb
        npm install -g mocha
        rm node_modules/@userdashboard/dashboard/*.js
        rm -rf node_modules/@userdashboard/dashboard/languages
        rm -rf node_modules/@userdashboard/dashboard/src
        cp $HERE/*.js node_modules/@userdashboard/dashboard
        cp -R $HERE/src/ node_modules/@userdashboard/dashboard/src/
        cp -R $HERE/languages/ node_modules/@userdashboard/dashboard/languages/
        echo "global.applicationPath = __dirname" > main.js
    - name: Test unencrypted MongoDB storage
      run: mocha --retries 2 --file main.js --bail --exit --full-trace --recursive --timeout 90000000 "./node_modules/@userdashboard/**/{,!(public)}/*.test.js"
      working-directory: "/tmp/project"
      env:
        NODE_ENV: "testing"
        FAST_START: "true"
        DASHBOARD_SERVER: "http://localhost:9000"
        DOMAIN: "localhost"
        STORAGE: "@userdashboard/storage-mongodb"
        MONGODB_URL: "mongodb://localhost:27017"
        MONGODB_DATABASE: "dashboard"
        GENERATE_SITEMAP_TXT: "false"
        GENERATE_API_TXT: "false"
        LOG_LEVEL: "info,warn,error,log"
    - name: Test encrypted MongoDB storage
      run: mocha --retries 2 --file main.js --bail --exit --full-trace --recursive --timeout 90000000 "./node_modules/@userdashboard/**/{,!(public)}/*.test.js"
      working-directory: "/tmp/project"
      env:
        NODE_ENV: "testing"
        FAST_START: "true"
        DASHBOARD_SERVER: "http://localhost:9000"
        DOMAIN: "localhost"
        STORAGE: "@userdashboard/storage-mongodb"
        MONGODB_URL: "mongodb://localhost:27017"
        MONGODB_DATABASE: "dashboard"
        GENERATE_SITEMAP_TXT: "false"
        GENERATE_API_TXT: "false"
        ENCRYPTION_SECRET: "12345678901234567890123456789012"
        ENCRYPTION_SECRET_IV: "1234123412341234"
        LOG_LEVEL: "info,warn,error,log"
